spring.application.name=ratingsystem
spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:/db/migration
spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

logging.level.org.springframework.jdbc.datasource.init=DEBUG

springdoc.default-produces-media-type=application/json

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tonkopolina@gmail.com
spring.mail.password=ryby byta fwuq uczx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.secret_key=ZTg5NDdkZmY0MGM3YmJkZjNmNTM1M2NlZjcxMzI2ZDRjYmRiMmEwMzEwY2NkNzZkMjg3MTMxMTM3ODYyNGUwNw==