spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${vcap.services.postgres.credentials.hostname}:${vcap.services.postgres.credentials.port}/${vcap.services.postgres.credentials.dbname}
spring.datasource.username=${vcap.services.postgres.credentials.username}
spring.datasource.password=${vcap.services.postgres.credentials.password}
spring.sql.init.mode=always

logging.level.org.springframework.cloud=DEBUG

spring.data.redis.ssl.enabled=true
spring.data.redis.host=${vcap.services.redis.credentials.hostname}
spring.data.redis.port=${vcap.services.redis.credentials.port}
spring.data.redis.password=${vcap.services.redis.credentials.password}
spring.data.redis.url=${vcap.services.redis.credentials.uri}